const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  auth: {
    login: (email, password) => ipcRenderer.invoke("auth:login", { email, password }),
    restoreSession: (user) => ipcRenderer.invoke("auth:restoreSession", user),
    logout: () => ipcRenderer.invoke("auth:logout"),
    listUsers: () => ipcRenderer.invoke("auth:listUsers"),
  },
  products: {
    getAll: () => ipcRenderer.invoke("products:getAll"),
    getByBarcode: (barcode) => ipcRenderer.invoke("products:getByBarcode", barcode),
    getCategories: () => ipcRenderer.invoke("products:getCategories"),
    create: (product) => ipcRenderer.invoke("products:create", product),
    update: (product) => ipcRenderer.invoke("products:update", product),
    delete: (id) => ipcRenderer.invoke("products:delete", id),
    adjustStock: (id, delta, reason) => ipcRenderer.invoke("products:adjustStock", { id, delta, reason }),
  },
  sales: {
    create: (sale) => ipcRenderer.invoke("sales:create", sale),
    getRecent: (limit) => ipcRenderer.invoke("sales:getRecent", limit),
    getSummary: () => ipcRenderer.invoke("sales:getSummary"),
    getWeeklyTrend: () => ipcRenderer.invoke("sales:getWeeklyTrend"),
    getItems: (saleId) => ipcRenderer.invoke("sales:getItems", saleId),
  },
  customers: {
    getAll: () => ipcRenderer.invoke("customers:getAll"),
    create: (customer) => ipcRenderer.invoke("customers:create", customer),
    update: (customer) => ipcRenderer.invoke("customers:update", customer),
    delete: (id) => ipcRenderer.invoke("customers:delete", id),
    addPayment: (payment) => ipcRenderer.invoke("customers:addPayment", payment),
    getStatement: (id) => ipcRenderer.invoke("customers:getStatement", id),
    getPurchaseHistory: (id) => ipcRenderer.invoke("customers:getPurchaseHistory", id),
  },
  suppliers: {
    getAll: () => ipcRenderer.invoke("suppliers:getAll"),
    create: (supplier) => ipcRenderer.invoke("suppliers:create", supplier),
    update: (supplier) => ipcRenderer.invoke("suppliers:update", supplier),
    delete: (id) => ipcRenderer.invoke("suppliers:delete", id),
    addPayment: (payment) => ipcRenderer.invoke("suppliers:addPayment", payment),
    getStatement: (id) => ipcRenderer.invoke("suppliers:getStatement", id),
  },
  purchases: {
    getAll: () => ipcRenderer.invoke("purchases:getAll"),
    getItems: (id) => ipcRenderer.invoke("purchases:getItems", id),
    getReturns: (id) => ipcRenderer.invoke("purchases:getReturns", id),
    create: (purchase) => ipcRenderer.invoke("purchases:create", purchase),
    receive: (id) => ipcRenderer.invoke("purchases:receive", id),
    updateStatus: (id, status) => ipcRenderer.invoke("purchases:updateStatus", { id, status }),
    createReturn: (ret) => ipcRenderer.invoke("purchases:createReturn", ret),
  },
  expenses: {
    getAll: () => ipcRenderer.invoke("expenses:getAll"),
    getCategories: () => ipcRenderer.invoke("expenses:getCategories"),
    createCategory: (name) => ipcRenderer.invoke("expenses:createCategory", name),
    create: (expense) => ipcRenderer.invoke("expenses:create", expense),
    update: (expense) => ipcRenderer.invoke("expenses:update", expense),
    delete: (id) => ipcRenderer.invoke("expenses:delete", id),
    attachReceipt: () => ipcRenderer.invoke("expenses:attachReceipt"),
    openReceipt: (path) => ipcRenderer.invoke("expenses:openReceipt", path),
    getSummary: () => ipcRenderer.invoke("expenses:getSummary"),
  },
  reports: {
    getRevenueVsExpenses: () => ipcRenderer.invoke("reports:getRevenueVsExpenses"),
    getTopProducts: (limit) => ipcRenderer.invoke("reports:getTopProducts", limit),
    getCategorySales: () => ipcRenderer.invoke("reports:getCategorySales"),
    getProfitSummary: () => ipcRenderer.invoke("reports:getProfitSummary"),
    getSalesReport: (range) => ipcRenderer.invoke("reports:getSalesReport", range),
    getPurchaseReport: (range) => ipcRenderer.invoke("reports:getPurchaseReport", range),
    getProfitLoss: (params) => ipcRenderer.invoke("reports:getProfitLoss", params),
    getExpenseReport: (range) => ipcRenderer.invoke("reports:getExpenseReport", range),
    getInventoryReport: () => ipcRenderer.invoke("reports:getInventoryReport"),
    getLowStockReport: () => ipcRenderer.invoke("reports:getLowStockReport"),
    getCustomerReport: () => ipcRenderer.invoke("reports:getCustomerReport"),
    getSupplierReport: () => ipcRenderer.invoke("reports:getSupplierReport"),
  },
  settings: {
    getAll: () => ipcRenderer.invoke("settings:getAll"),
    update: (updates) => ipcRenderer.invoke("settings:update", updates),
    getPrinters: () => ipcRenderer.invoke("settings:getPrinters"),
  },
  backup: {
    export: () => ipcRenderer.invoke("backup:export"),
    restore: () => ipcRenderer.invoke("backup:restore"),
    getHistory: () => ipcRenderer.invoke("backup:getHistory"),
    runNow: () => ipcRenderer.invoke("backup:runNow"),
  },
  sync: {
    getStatus: () => ipcRenderer.invoke("sync:getStatus"),
    triggerNow: () => ipcRenderer.invoke("sync:triggerNow"),
    setAutoSync: (enabled) => ipcRenderer.invoke("sync:setAutoSync", enabled),
    onConnectionRestored: () => ipcRenderer.invoke("sync:onConnectionRestored"),
  },
  permissions: {
    getMatrix: () => ipcRenderer.invoke("permissions:getMatrix"),
    getMine: () => ipcRenderer.invoke("permissions:getMine"),
    update: (change) => ipcRenderer.invoke("permissions:update", change),
  },
  audit: {
    getAll: (params) => ipcRenderer.invoke("audit:getAll", params),
    getLoginHistory: (limit) => ipcRenderer.invoke("audit:getLoginHistory", limit),
  },
  auth_admin: {
    createUser: (user) => ipcRenderer.invoke("auth:createUser", user),
    setUserActive: (id, active) => ipcRenderer.invoke("auth:setUserActive", { id, active }),
    setUserRole: (id, role) => ipcRenderer.invoke("auth:setUserRole", { id, role }),
  },
});
